### ISSUE TITLE
"Can't have lua running in two host threads at a time!"

### ISSUE THREAD

**Issue by JoystickHero1** [alexjpaz-twitch/bizhawk-crowd-shuffler#23]
I've run into this issue with Bizhawk releases 6 and 6.1. When resuming a game (IE, switching to a game with an existing save state), I get the following error on a prompt:

![image](https://user-images.githubusercontent.com/20269957/130656625-688f93f8-32b0-4f73-ab6e-94be82e4d6a5.png)

After dismissing the error, everything continues as expected, until the next game switch. Not sure if this is a more widespread issue or what I may do to correct this.

**Comment by alexjpaz** [comment]
FWIW - I've only tested the bizhawk shuffler with 2.5.x releases.

**Comment by JoystickHero1** [comment]
Can confirm this works with 2.5.x, may want to update the readme to suggest 2.6 or greater does not work for now?
