### ISSUE TITLE
Swapping halts when it encounters a bin file

### ISSUE THREAD

**Issue by kkwak-uno** [alexjpaz-twitch/bizhawk-crowd-shuffler#24]
If a file that requires a bin file in addition to a cue file to run is in the CurrentRoms directory and it's chosen as the file to swap to, the process stops as it brings up a menu to select what type of emulator the file should be used in and even if the correct emulator is selected, the emulator does not run anything. There needs to be some handling to ignore bin files in this directory.

**Comment by alexjpaz** [comment]
A workaround I have found for that is to edit the cue file to look for the bin file in the folder above or in another folder. It is less than ideal. 

I can look into adding a configuration option to filter out files (see https://github.com/alexjpaz-twitch/bizhawk-crowd-shuffler/blob/main/src/index.js#L60-L63)

**Comment by alexjpaz** [comment]
Should be fixed in the `v0.11.0` release
